name: Build exe

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-exe:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Download Launch4j
        run: |
          wget https://sourceforge.net/projects/launch4j/files/launch4j-3/3.14/launch4j-3.14-linux-x64.tgz
          tar -xvf launch4j-3.14-linux-x64.tgz