name: create-release-with-msi-installer

on:
  pull_request:
    branches:
      - main

jobs:
  create-windows-installer-release:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install go-msi
        run: choco install -y "go-msi"

      - name: Build Windows Installer MSI
        uses: AliceOh/CreateWindowsInstaller@1.0.0
        with:
          exefile: 'PhasmoChallengeGenerator.exe'

      - name: Upload MSI to release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest
          prerelease: true
          title: "Phasmo-Challenge-Generator-*"
          files: |
            PhasmoChallengeGenerator.exe.msi