name: create-release-with-msi-installer

on:
  pull_request:
    types:
      - closed

jobs:
  create-windows-installer-release:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install go-msi
        if: contains(github.event.pull_request.title, 'RELEASE')
        run: choco install -y "go-msi"

      - name: Build Windows Installer MSI
        if: contains(github.event.pull_request.title, 'RELEASE')
        uses: AliceOh/CreateWindowsInstaller@1.0.0
        with:
          exefile: 'PhasmoChallengeGenerator.exe'

      - name: Rename MSI-Installer file
        if: contains(github.event.pull_request.title, 'RELEASE')
        run: mv PhasmoChallengeGenerator.exe.msi Phasmophobia-Challenge-Generator.msi

      - name: Upload MSI to release
        if: contains(github.event.pull_request.title, 'RELEASE')
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest
          draft: true
          prerelease: true
          title: "Phasmo-Challenge-Generator-*"
          files: |
            Phasmophobia-Challenge-Generator.msi